### ISSUE TITLE
Error then opening!

### ISSUE THREAD

**Issue by Kiudgriujian** [Vaeb/VaeBot#11]
```
2018-08-19T08:20:05.167498+00:00 app[worker.1]: Error: ENOENT: no such file or directory, scandir '/home/flipflop8421/files/discordExp/VaeBot/commands/'
2018-08-19T08:20:05.167500+00:00 app[worker.1]:     at Object.fs.readdirSync (fs.js:904:18)
2018-08-19T08:20:05.167503+00:00 app[worker.1]:     at Object.exports.grabFiles (/app/Util.js:545:30)
2018-08-19T08:20:05.167504+00:00 app[worker.1]:     at Object.exports.bulkRequire (/app/Util.js:560:31)
2018-08-19T08:20:05.167506+00:00 app[worker.1]:     at Object.exports.initCommands (/app/core/ManageCommands.js:60:10)
2018-08-19T08:20:05.167507+00:00 app[worker.1]:     at Object.<anonymous> (/app/index.js:383:6)
2018-08-19T08:20:05.167508+00:00 app[worker.1]:     at Module._compile (module.js:652:30)
2018-08-19T08:20:05.167510+00:00 app[worker.1]:     at Object.Module._extensions..js (module.js:663:10)
2018-08-19T08:20:05.167511+00:00 app[worker.1]:     at Module.load (module.js:565:32)
2018-08-19T08:20:05.167512+00:00 app[worker.1]:     at tryModuleLoad (module.js:505:12)
2018-08-19T08:20:05.167513+00:00 app[worker.1]:     at Function.Module._load (module.js:497:3)
```
what does it mean?

**Comment by LuaLG** [comment]
`no such file or directory, scandir '/home/flipflop8421/files/discordExp/VaeBot/commands/'`

**Comment by Iwqn** [comment]
> `no such file or directory, scandir '/home/flipflop8421/files/discordExp/VaeBot/commands/'`
> 
> That's what it means

I have the same error
